language: php
os: linux
dist: xenial
before_deploy: ./iac/before_deploy.sh
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./iac/deploy.sh $DEV_LOCATION
    on:
      branch: feature/setup-travis.ci-basic-integration
  - provider: script
    skip_cleanup: true
    script: bash ./iac/deploy.sh $PRD_LOCATION
    on:
      branch: master